# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tonyt\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 1000)
        self.HaloBtn = QtWidgets.QPushButton(Dialog)
        self.HaloBtn.setGeometry(QtCore.QRect(30, 900, 141, 71))
        self.HaloBtn.setObjectName("HaloBtn")
        self.ImageLabel = QtWidgets.QLabel(Dialog)
        self.ImageLabel.setGeometry(QtCore.QRect(140, 290, 411, 521))
        self.ImageLabel.setText("")
        self.ImageLabel.setPixmap(QtGui.QPixmap("C:\\Users\\tonyt\\Downloads/pngtree-search-icon-image_1344447.jpg"))
        self.ImageLabel.setObjectName("ImageLabel")
        self.UploadImageBtn = QtWidgets.QPushButton(Dialog)
        self.UploadImageBtn.setGeometry(QtCore.QRect(230, 110, 191, 51))
        self.UploadImageBtn.setObjectName("UploadImageBtn")

        self.retranslateUi(Dialog)
        self.HaloBtn.clicked.connect(Dialog.accept) # type: ignore
        self.UploadImageBtn.clicked.connect(Dialog.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.HaloBtn.setText(_translate("Dialog", "Show Halo"))
        self.UploadImageBtn.setText(_translate("Dialog", "Upload Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
